language: python
python:
- '2.7'
script:
- sudo apt-get install python-dev -y
- cd $TRAVIS_BUILD_DIR
- git clean -fXd
- pip install -r requirements.txt -t .
- pip install python-Levenshtein
- rm -rf numpy boto*
- ls | grep dist-info | xargs rm -rf
- zip -r9 ~/Release.zip . -x \*.git\*
- mkdir dist
- mv ~/Release.zip dist/
before_deploy:
  - git config --local user.name "m0ngr31"
  - git config --local user.email "joe@ipson.me"
  - git tag "$(date +'%m.%d.%Y')-$(git log --format=%h -1)"
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: eoxDYqEtdRTIb2ZWqH68FuWDB6v2UFtTNJ5OcYGNByeMws7djkK20NtRaNljMmDwfkhYK4biCwSul3A9KAdWntTRe1JKmxwlNdHUVQaDfuoZ/HCNeTe59RLN5JITQk/ppgLoJ+3BwcXymWkWb8xI1M5dv5cuQE67WV9jcaW28dcMsoPQyDGdTabtYU+47TNSKuYGTM7QxZMhCactfmNUrsBZceQ6qjjHlV/xbM+ZR2IeIT49Pua5xRcj4CNr0Ggt/KD+Cg/nV9XIC9IUHjn9lPD3Tb7kmRTvikOM+R04nIbTAFNap0yHHxA2zzxoQdiXyfscZilXtfVmrel6uJNp62adLQFGAd6af3zfHbzcwQu06Aml4jV+15sQVvXTL7NKN9rTkem+/rs1pO5H5Wnq6D4WTajVZz1kGDz88q35q0uRn4ghf1ZDcedX0AImqSGiOCX6DgJOOt8PDIeLgy+ajXnSXxAIrJLzAEgwBgaUElx5b3yeWQWCwWW8/PMkwJBCTZxI+Z1DFnNH8BU1KueftBw08k/1Owz0CsN8XnmQ3Ls8K2+6yMHl49Ci8kU+T8PnbNeT7FW4Kime9aJUfKlcrdg5TgapuYgEhP2ArYXUOs4HV2NahIRnOGoEoMrZ5+t8mSIJmY7Z9qLnym7EbK1EJx5cI4tTGgkGs1oeDc0Frl4=
  file: $TRAVIS_BUILD_DIR/dist/Release.zip
  on:
    repo: m0ngr31/kodi-alexa
